### ISSUE TITLE
Error trying to deploy project

### ISSUE THREAD

**Issue by phillipnunes** [infrastructure-components/infrastructure-components#1]
Hi.

I installed the package infrastructure-components in the project using `npm install --save infrastructure-components`, and I tried to deploy to my instance of now serverless, but I am getting this error:

```
error /tmp/731ab8ad/node_modules/infrastructure-components: Command failed.
--
Aug 14 2019 15:22:20:547 | ...sitemap-builder.js | Exit code: 127
Aug 14 2019 15:22:20:547 | ...sitemap-builder.js | Command: icinstall install
Aug 14 2019 15:22:20:547 | ...sitemap-builder.js | Arguments:
Aug 14 2019 15:22:20:547 | ...sitemap-builder.js | Directory: /tmp/731ab8ad/node_modules/infrastructure-components
Aug 14 2019 15:22:20:547 | ...sitemap-builder.js | Output:
Aug 14 2019 15:22:20:547 | ...sitemap-builder.js | /bin/sh: icinstall: command not found
Aug 14 2019 15:22:20:548 | ...sitemap-builder.js | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Aug 14 2019 15:22:20:619 | ...sitemap-builder.js | Error: Exited with 127
Aug 14 2019 15:22:20:619 | ...sitemap-builder.js | at ChildProcess.child.on (/tmp/3a386d720362b76d/.build-utils/.builder/node_modules/@now/node/dist/index.js:78176:24)
Aug 14 2019 15:22:20:619 | ...sitemap-builder.js | at emitTwo (events.js:126:13)
Aug 14 2019 15:22:20:619 | ...sitemap-builder.js | at ChildProcess.emit (events.js:214:7)
Aug 14 2019 15:22:20:619 | ...sitemap-builder.js | at maybeClose (internal/child_process.js:925:16)
Aug 14 2019 15:22:20:619 | ...sitemap-builder.js | at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
Aug 14 2019 15:22:20:696 | ...sitemap-builder.js | done
```
The only change in the project is this package, nothing else.

Does anyone have some clue about this problem?
Thanks!

**Comment by frankzickert** [comment]
Hi,

There are two things here:

1.) the missing icinstall command is part of the library 'infrastructure-scripts'. Both libraries work together.

Why is that?

- Infrastructure-Components provide the React-components to be used in the code and to be deployed alongside the project.
- Infrastructure-Scripts contain the build and deployment scripts. For these not required during runtime, install this library as dev-dependency only. (`npm i -D infrastructure-components`)

2.) Currently, infrastructure-components work with "plain" AWS. Zeit Now brings its own deployment scripts.

What you could try:

- Run `npm run scripts build src/index.tsx`(a command from infrastructure-scripts)
- you'll get all the output files in the build directory. You could then put them onto Zeit Now. 

Hope this helps.
Best
Frank
